import type { InvestigationPreview } from '@mammoth/domain';

export function renderInvestigationPreview(
  preview: InvestigationPreview,
): string {
  const list = (values: readonly string[]): string =>
    values.map((value) => `- ${value}`).join('\n');
  return [
    '# Mammoth investigation preview',
    '',
    `> ${preview.question}`,
    '',
    'No external research has run. Network access, cloud providers, retrieval, paid effects, and experiment execution remain blocked pending explicit approval.',
    '',
    '## Interpretation',
    '',
    preview.interpretation.objective,
    '',
    `Decision criterion: ${preview.interpretation.decisionCriterion}`,
    '',
    '## Proposed research team',
    '',
    ...preview.proposedTeam.flatMap((role) => [
      `### ${role.title}`,
      '',
      role.mission,
      '',
      `Independence: ${role.independence}`,
      '',
    ]),
    '## Ambiguities',
    '',
    list(preview.ambiguities),
    '',
    '## Assumptions',
    '',
    list(preview.assumptions),
    '',
    '## Research plan',
    '',
    '### Subquestions',
    '',
    list(preview.plan.subquestions),
    '',
    '### Planned searches',
    '',
    list(preview.plan.searchQueries),
    '',
    '### Falsification and contradiction',
    '',
    list([
      ...preview.plan.falsificationChecks,
      ...preview.plan.contradictionChecks,
    ]),
    '',
    '### Proposed report',
    '',
    list(preview.plan.reportSections),
    '',
    '## Requested authority',
    '',
    `Status: **${preview.requestedAuthority.status}**`,
    '',
    `Maximum time: ${String(preview.requestedAuthority.maxTimeMinutes)} minutes`,
    '',
    `Maximum spend: $${preview.requestedAuthority.maxSpendUsd.toFixed(2)} USD`,
    '',
    `Requested tools: ${preview.requestedAuthority.requestedTools.join('; ')}`,
    '',
    `Requested network access: ${preview.requestedAuthority.requestedNetworkAccess.join('; ')}`,
    '',
    '## Experiments',
    '',
    preview.experiments.statement,
    '',
    '## Approval choices',
    '',
    ...preview.approvalChoices.map(
      (choice) => `- **${choice.choice}** — ${choice.effect}`,
    ),
    '',
    `Preview digest: \`${preview.previewDigest}\``,
    '',
  ].join('\n');
}
